default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV.fetch('POSTGRES_DATABASE', 'code-challenge-levee') %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: <%= ENV.fetch("POSTGRES_USER", 'postgres') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', 'postgres') %>
  host: <%= ENV.fetch("POSTGRES_HOST", 'localhost') %>
  port: 5432

development:
  <<: *default
  database: docker_development
test:
  <<: *default
  database: docker_test

production:
  <<: *default
  database: docker_production
  username: docker
  password: <%= ENV['DOCKER_DATABASE_PASSWORD'] %>
